version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3666:80"  # Mappe le port 80 du conteneur sur le port 3666 de l'hôte
    container_name: mon-app-sportive-frontend
    restart: unless-stopped