version: '3.8'

services:
  frontend:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    # Suppression des volumes problématiques
    # Les fichiers sont copiés lors du build via le Dockerfile