version: '3.8'

services:
  frontend:
    build: .
    ports:
      - "3666:3000"  # Port externe 3666 mappé sur le port 3000 du conteneur
    environment:
      - NODE_ENV=production
    restart: unless-stopped