version: '3.8'

services:
  frontend:
    build: .
    ports:
      - "8080:8080"
    restart: unless-stopped
    depends_on:
      - backend

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "3002:3001"
    restart: unless-stopped
    depends_on:
      - db
    environment:
      - BACKEND_PORT=3001
      - FRONTEND_URL=http://localhost:8080
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=sporflow_user
      - DB_PASSWORD=change_this_password
      - DB_NAME=sporflow_db
      - JWT_SECRET=this-is-a-super-secret-key-and-you-should-change-it

  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_DB: sporflow_db
      POSTGRES_USER: sporflow_user
      POSTGRES_PASSWORD: change_this_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5436:5432"

volumes:
  postgres_data: