version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3666:3000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    volumes:
      - node_modules:/app/node_modules
      
volumes:
  node_modules: