version: '3.8'

services:
  frontend:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://backend:3001/api

  backend:
    build:
      context: ./backend
    ports:
      - "3002:3001"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USER=sporflow_user
      - DB_PASSWORD=change_this_password
      - DB_NAME=sporflow_db
      - JWT_SECRET=this-is-a-super-secret-key-and-you-should-change-it

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: sporflow_db
      POSTGRES_USER: sporflow_user
      POSTGRES_PASSWORD: change_this_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/init:/docker-entrypoint-initdb.d
    ports:
      - "5436:5432"

volumes:
  postgres_data: