// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://wgbppimryopbejupoydj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndnYnBwaW1yeW9wYmVqdXBveWRqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMyMTU2OTksImV4cCI6MjA2ODc5MTY5OX0.2Loafsj0k5EN_-4Blsfmfc1cVaeP1RZEYV9aqN6GtJM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);